// This file was generated by the "yardl" tool. DO NOT EDIT.

#pragma once
#include <array>
#include <complex>
#include <memory>
#include <optional>
#include <variant>
#include <vector>

#include "../yardl/detail/ndjson/reader_writer.h"
#include "../protocols.h"

namespace mrd::ndjson {
// NDJSON writer for the Mrd protocol.
// The MRD Protocol
class MrdWriter : public mrd::MrdWriterBase, yardl::ndjson::NDJsonWriter {
  public:
  MrdWriter(std::ostream& stream)
      : yardl::ndjson::NDJsonWriter(stream, schema_) {
  }

  MrdWriter(std::string file_name)
      : yardl::ndjson::NDJsonWriter(file_name, schema_) {
  }

  void Flush() override;

  protected:
  void WriteHeaderImpl(std::optional<mrd::Header> const& value) override;
  void WriteDataImpl(mrd::StreamItem const& value) override;
  void EndDataImpl() override {}
  void CloseImpl() override;
};

// NDJSON reader for the Mrd protocol.
// The MRD Protocol
class MrdReader : public mrd::MrdReaderBase, yardl::ndjson::NDJsonReader {
  public:
  MrdReader(std::istream& stream, bool skip_completed_check=false)
      : mrd::MrdReaderBase(skip_completed_check), yardl::ndjson::NDJsonReader(stream, schema_) {
  }

  MrdReader(std::string file_name, bool skip_completed_check=false)
      : mrd::MrdReaderBase(skip_completed_check), yardl::ndjson::NDJsonReader(file_name, schema_) {
  }

  protected:
  void ReadHeaderImpl(std::optional<mrd::Header>& value) override;
  bool ReadDataImpl(mrd::StreamItem& value) override;
  void CloseImpl() override;
};

// NDJSON writer for the MrdNoiseCovariance protocol.
// Protocol for serializing a noise covariance matrix
class MrdNoiseCovarianceWriter : public mrd::MrdNoiseCovarianceWriterBase, yardl::ndjson::NDJsonWriter {
  public:
  MrdNoiseCovarianceWriter(std::ostream& stream)
      : yardl::ndjson::NDJsonWriter(stream, schema_) {
  }

  MrdNoiseCovarianceWriter(std::string file_name)
      : yardl::ndjson::NDJsonWriter(file_name, schema_) {
  }

  void Flush() override;

  protected:
  void WriteNoiseCovarianceImpl(mrd::NoiseCovariance const& value) override;
  void CloseImpl() override;
};

// NDJSON reader for the MrdNoiseCovariance protocol.
// Protocol for serializing a noise covariance matrix
class MrdNoiseCovarianceReader : public mrd::MrdNoiseCovarianceReaderBase, yardl::ndjson::NDJsonReader {
  public:
  MrdNoiseCovarianceReader(std::istream& stream, bool skip_completed_check=false)
      : mrd::MrdNoiseCovarianceReaderBase(skip_completed_check), yardl::ndjson::NDJsonReader(stream, schema_) {
  }

  MrdNoiseCovarianceReader(std::string file_name, bool skip_completed_check=false)
      : mrd::MrdNoiseCovarianceReaderBase(skip_completed_check), yardl::ndjson::NDJsonReader(file_name, schema_) {
  }

  protected:
  void ReadNoiseCovarianceImpl(mrd::NoiseCovariance& value) override;
  void CloseImpl() override;
};

} // namespace mrd::ndjson
