set shell := ['bash', '-ceuo', 'pipefail']

cpp_version := "20"
build_type := "RelWithDebInfo"

matlab := "disabled"
matlab-test-cmd := if matlab != "disabled" { "run-matlab-command buildtool" } else { "echo Skipping MATLAB tests..." }
cross-recon-test-cmd := if matlab != "disabled" { "MRD_MATLAB_ENABLED=true ./test-all.sh" } else { "./test-all.sh" }

@default: test

@configure:
    mkdir -p cpp/build; \
    cd cpp/build; \
    cmake -GNinja \
        -D CMAKE_BUILD_TYPE:STRING={{ build_type }} \
        -D CMAKE_CXX_STANDARD:STRING={{ cpp_version }} \
        -D CMAKE_INSTALL_PREFIX=$(conda info --json | jq -r .default_prefix) \
        ..

@build: configure generate
    cd cpp/build && ninja

@install: test
    cd cpp/build && ninja install

@convert-xsd:
    wget -O ismrmrd.xsd https://raw.githubusercontent.com/ismrmrd/ismrmrd/master/schema/ismrmrd.xsd
    python utils/xsd-to-yardl.py ismrmrd.xsd > model/mrd_header.yml
    rm ismrmrd.xsd

@generate:
    printf '# Generated by `just generate` from the top-level VERSION file. Do not edit manually.\n__version__ = "%s"\n' "$(cat VERSION)" > python/mrd/_version.py
    cd model && yardl generate

@conda-cpp-test: build
    cd cpp/build; \
    PATH=./:$PATH ../conda/run_test.sh

@conda-python-test: generate
    cd python; \
    ./conda/run_test.sh

@matlab-test: generate
    cd matlab; \
    {{ matlab-test-cmd }}

@end-to-end-test: build
    cd test; \
    {{ cross-recon-test-cmd }}

@upgrade-test: generate
    bash test/upgrade/test-upgrade.sh

@test: build conda-cpp-test conda-python-test matlab-test end-to-end-test upgrade-test

validate-with-no-changes: test
    #!/usr/bin/env bash
    set -euo pipefail

    if [[ `git status --porcelain` ]]; then
      echo "ERROR: Found uncommitted changes:"
      git status --porcelain
      exit 1
    fi

@clean:
    rm -rf cpp/conda/build_pkg/
    rm -rf python/conda/build_pkg/
    rm -rf python/dist python/mrd.egg-info/
    pushd cpp/build && ninja clean && popd

@start-docs-website:
    cd docs && npm install && npm run docs:dev

@build-docs:
    cd docs && npm install && npm run docs:build

@build-cpp-conda-package:
    bash -il ./utils/conda/setup-conda-build.sh; \
    cd cpp/conda; \
    ../../utils/conda/package.sh

@build-python-conda-package:
    bash -il ./utils/conda/setup-conda-build.sh; \
    cd python/conda; \
    ../../utils/conda/package.sh

@build-pypi-package:
    ./utils/pypi/package.sh

@localinstall-python-package:
    cd python; \
    pip install .

@build-matlab-toolbox:
    cd matlab; \
    run-matlab-command buildtool

@build-cmake-fetch-src:
    tar -czf mrd-cmake-src-$(cat VERSION).tar.gz -C ./cpp/ CMakeLists.txt mrd/ mrd-tools/

@build-docker-images *PARAMETERS:
    ./docker/build-images.sh {{PARAMETERS}}

@test-docker-images:
    ./docker/test-docker-images.sh
