{% set version = os.environ['MRD_VERSION_STRING'].replace('-', '') %}
{% set repo = 'https://github.com/ismrmrd/mrd' %}

package:
  name: mrd-python
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script_env:
    - MRD_VERSION_STRING

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.22.0
    - pillow >=9.2.0

test:
  imports:
    - mrd
    - mrd.tools.phantom
    - mrd.tools.stream_recon

about:
  home: {{ repo }}
  license: MIT
  summary: 'Python SDK for the ISMRM Raw Data Format (MRD)'
  description: |
    Python interface and utilities for working with ISMRM Raw Data.
  dev_url: {{ repo }}
  doc_url: {{ repo }}
  doc_source_url: {{repo}}/blob/main/README.md
