{% set version = os.environ['MRD_VERSION_STRING'].replace('-', '') %}

package:
  name: mrd
  version: {{ version }}

source:
  path: ../

build:
  script_env:
    - MRD_VERSION_STRING

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - fftw=3.3.*
    - howardhinnant_date=3.0.3
    - hdf5=1.14.*
    - imagemagick>=7.1.2_8
    - ismrmrd>=1.15.0
    - nlohmann_json=3.12.0
    - xtensor=0.27.1
  run:
    - fftw=3.3.*
    - hdf5=1.14.*
    - imagemagick>=7.1.2_8
    - ismrmrd>=1.15.0

about:
  home: https://ismrmrd.github.io/mrd
  license: MIT
  summary: 'ISMRM Raw Data Format (MRD)'
  description: |
    Libraries and tools for working with ISMRM Raw Data.
  dev_url: https://github.com/ismrmrd/mrd
  doc_url: https://ismrmrd.github.io/mrd
  doc_source_url: https://github.com/ismrmrd/mrd/blob/main/README.md
