{% set version = os.environ['MRD_VERSION_STRING'].replace('-', '') %}

package:
  name: mrd
  version: {{ version }}

source:
  path: ../

build:
  script_env:
    - MRD_VERSION_STRING

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - fftw=3.3.9
    - fmt=8.1.1
    - howardhinnant_date=3.0.1
    - hdf5=1.10.6
    - imagemagick=7.0.11_13
    - ismrmrd>=1.14.2
    - nlohmann_json=3.11.2
    - xtensor=0.24.7
    - xtensor-fftw=0.2.5
  run:
    - fmt=8.1.1
    - hdf5=1.10.6
    - imagemagick=7.0.11_13
    - ismrmrd>=1.14.2
    - fftw=3.3.9

about:
  home: https://ismrmrd.github.io/mrd
  license: MIT
  summary: 'ISMRM Raw Data Format (MRD)'
  description: |
    Libraries and tools for working with ISMRM Raw Data.
  dev_url: https://github.com/ismrmrd/mrd
  doc_url: https://ismrmrd.github.io/mrd
  doc_source_url: https://github.com/ismrmrd/mrd/blob/main/README.md
