% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef AcquisitionBucket < handle
  properties
    data
    ref
    datastats
    refstats
    waveforms
  end

  methods
    function self = AcquisitionBucket(kwargs)
      arguments
        kwargs.data = mrd.Acquisition.empty();
        kwargs.ref = mrd.Acquisition.empty();
        kwargs.datastats = mrd.EncodingLimitsType.empty();
        kwargs.refstats = mrd.EncodingLimitsType.empty();
        kwargs.waveforms = mrd.WaveformUint32.empty();
      end
      self.data = kwargs.data;
      self.ref = kwargs.ref;
      self.datastats = kwargs.datastats;
      self.refstats = kwargs.refstats;
      self.waveforms = kwargs.waveforms;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.AcquisitionBucket") && ...
        isequal({self.data}, {other.data}) && ...
        isequal({self.ref}, {other.ref}) && ...
        isequal({self.datastats}, {other.datastats}) && ...
        isequal({self.refstats}, {other.refstats}) && ...
        isequal({self.waveforms}, {other.waveforms});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.AcquisitionBucket();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
