% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef AcquisitionPrototype < handle
  % Specifies header and data size of an acquisition, without the actual data.
  properties
    % Acquisition header template
    head
    % Sample counts by coil
    data_sample_counts
  end

  methods
    function self = AcquisitionPrototype(kwargs)
      arguments
        kwargs.head = mrd.AcquisitionHeader();
        kwargs.data_sample_counts = uint32.empty();
      end
      self.head = kwargs.head;
      self.data_sample_counts = kwargs.data_sample_counts;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.AcquisitionPrototype") && ...
        isequal({self.head}, {other.head}) && ...
        isequal({self.data_sample_counts}, {other.data_sample_counts});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.AcquisitionPrototype();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
