% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ADCEvent < handle
  % An ADC event
  properties
    % ID of the ADC event
    id
    % Number of samples
    num
    % The ADC dwell time, specified in nanoseconds
    dwell
    % Delay between start of block and first sample, specified in microseconds
    delay
    % Frequency offset of the ADC receiver relative to the system frequency,
    % specified in parts per million (ppm)
    freq_ppm
    % Phase offset of the ADC receiver proportional to the system frequency,
    % specified in rad/MHz
    phase_ppm
    % Frequency offset of the ADC receiver in absolute units, specified in Hz
    freq
    % Phase offset in absolute units, specified in radians
    phase
    % The shape ID
    phase_shape_id
  end

  methods
    function self = ADCEvent(kwargs)
      arguments
        kwargs.id = int32(0);
        kwargs.num = uint64(0);
        kwargs.dwell = single(0);
        kwargs.delay = uint64(0);
        kwargs.freq_ppm = double(0);
        kwargs.phase_ppm = double(0);
        kwargs.freq = double(0);
        kwargs.phase = double(0);
        kwargs.phase_shape_id = int32(0);
      end
      self.id = kwargs.id;
      self.num = kwargs.num;
      self.dwell = kwargs.dwell;
      self.delay = kwargs.delay;
      self.freq_ppm = kwargs.freq_ppm;
      self.phase_ppm = kwargs.phase_ppm;
      self.freq = kwargs.freq;
      self.phase = kwargs.phase;
      self.phase_shape_id = kwargs.phase_shape_id;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.ADCEvent") && ...
        isequal({self.id}, {other.id}) && ...
        isequal({self.num}, {other.num}) && ...
        isequal({self.dwell}, {other.dwell}) && ...
        isequal({self.delay}, {other.delay}) && ...
        isequal({self.freq_ppm}, {other.freq_ppm}) && ...
        isequal({self.phase_ppm}, {other.phase_ppm}) && ...
        isequal({self.freq}, {other.freq}) && ...
        isequal({self.phase}, {other.phase}) && ...
        isequal({self.phase_shape_id}, {other.phase_shape_id});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.ADCEvent();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
