% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef AnyNdArray < yardl.Union
  methods (Static)
    function res = NdArrayUint16(value)
      res = mrd.AnyNdArray(1, value);
    end

    function res = NdArrayInt16(value)
      res = mrd.AnyNdArray(2, value);
    end

    function res = NdArrayUint32(value)
      res = mrd.AnyNdArray(3, value);
    end

    function res = NdArrayInt32(value)
      res = mrd.AnyNdArray(4, value);
    end

    function res = NdArrayFloat(value)
      res = mrd.AnyNdArray(5, value);
    end

    function res = NdArrayDouble(value)
      res = mrd.AnyNdArray(6, value);
    end

    function res = NdArrayComplexFloat(value)
      res = mrd.AnyNdArray(7, value);
    end

    function res = NdArrayComplexDouble(value)
      res = mrd.AnyNdArray(8, value);
    end

    function z = zeros(varargin)
      elem = mrd.AnyNdArray(0, yardl.None);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end

  methods
    function res = isNdArrayUint16(self)
      res = self.index == 1;
    end

    function res = isNdArrayInt16(self)
      res = self.index == 2;
    end

    function res = isNdArrayUint32(self)
      res = self.index == 3;
    end

    function res = isNdArrayInt32(self)
      res = self.index == 4;
    end

    function res = isNdArrayFloat(self)
      res = self.index == 5;
    end

    function res = isNdArrayDouble(self)
      res = self.index == 6;
    end

    function res = isNdArrayComplexFloat(self)
      res = self.index == 7;
    end

    function res = isNdArrayComplexDouble(self)
      res = self.index == 8;
    end

    function eq = eq(self, other)
      eq = isa(other, "mrd.AnyNdArray") && all([self.index_] == [other.index_], 'all') && all([self.value] == [other.value], 'all');
    end

    function ne = ne(self, other)
      ne = ~self.eq(other);
    end

    function t = tag(self)
      tags_ = ["NdArrayUint16", "NdArrayInt16", "NdArrayUint32", "NdArrayInt32", "NdArrayFloat", "NdArrayDouble", "NdArrayComplexFloat", "NdArrayComplexDouble"];
      t = tags_(self.index_);
    end
  end
end
