% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef AnyNDArray < yardl.Union
  methods (Static)
    function res = NDArrayUint16(value)
      res = mrd.AnyNDArray(1, value);
    end

    function res = NDArrayInt16(value)
      res = mrd.AnyNDArray(2, value);
    end

    function res = NDArrayUint32(value)
      res = mrd.AnyNDArray(3, value);
    end

    function res = NDArrayInt32(value)
      res = mrd.AnyNDArray(4, value);
    end

    function res = NDArrayFloat(value)
      res = mrd.AnyNDArray(5, value);
    end

    function res = NDArrayDouble(value)
      res = mrd.AnyNDArray(6, value);
    end

    function res = NDArrayComplexFloat(value)
      res = mrd.AnyNDArray(7, value);
    end

    function res = NDArrayComplexDouble(value)
      res = mrd.AnyNDArray(8, value);
    end

    function z = zeros(varargin)
      elem = mrd.AnyNDArray(0, yardl.None);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end

  methods
    function res = isNDArrayUint16(self)
      res = self.index == 1;
    end

    function res = isNDArrayInt16(self)
      res = self.index == 2;
    end

    function res = isNDArrayUint32(self)
      res = self.index == 3;
    end

    function res = isNDArrayInt32(self)
      res = self.index == 4;
    end

    function res = isNDArrayFloat(self)
      res = self.index == 5;
    end

    function res = isNDArrayDouble(self)
      res = self.index == 6;
    end

    function res = isNDArrayComplexFloat(self)
      res = self.index == 7;
    end

    function res = isNDArrayComplexDouble(self)
      res = self.index == 8;
    end

    function eq = eq(self, other)
      eq = isa(other, "mrd.AnyNDArray") && all([self.index_] == [other.index_], 'all') && all([self.value] == [other.value], 'all');
    end

    function ne = ne(self, other)
      ne = ~self.eq(other);
    end

    function t = tag(self)
      tags_ = ["NDArrayUint16", "NDArrayInt16", "NDArrayUint32", "NDArrayInt32", "NDArrayFloat", "NDArrayDouble", "NDArrayComplexFloat", "NDArrayComplexDouble"];
      t = tags_(self.index_);
    end
  end
end
