% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ArrayImageType < uint64
  methods (Static)
    function v = MAGNITUDE
      v = mrd.ArrayImageType(1);
    end
    function v = PHASE
      v = mrd.ArrayImageType(2);
    end
    function v = REAL
      v = mrd.ArrayImageType(3);
    end
    function v = IMAG
      v = mrd.ArrayImageType(4);
    end
    function v = COMPLEX
      v = mrd.ArrayImageType(5);
    end

    function z = zeros(varargin)
      elem = mrd.ArrayImageType(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
