% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ArrayDimension < uint64
  methods (Static)
    function v = CHANNEL
      v = mrd.ArrayDimension(0);
    end
    function v = Z
      v = mrd.ArrayDimension(1);
    end
    function v = Y
      v = mrd.ArrayDimension(2);
    end
    function v = X
      v = mrd.ArrayDimension(3);
    end
    function v = FREQUENCY
      v = mrd.ArrayDimension(4);
    end
    function v = BASIS
      v = mrd.ArrayDimension(5);
    end
    function v = SAMPLES
      v = mrd.ArrayDimension(6);
    end
    function v = LOC
      v = mrd.ArrayDimension(7);
    end
    function v = S
      v = mrd.ArrayDimension(8);
    end
    function v = N
      v = mrd.ArrayDimension(9);
    end
    function v = E2
      v = mrd.ArrayDimension(10);
    end
    function v = E1
      v = mrd.ArrayDimension(11);
    end
    function v = E0
      v = mrd.ArrayDimension(12);
    end
    function v = TIME
      v = mrd.ArrayDimension(13);
    end

    function z = zeros(varargin)
      elem = mrd.ArrayDimension(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
