% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ArrayFlags < uint64
  methods (Static)
    function v = IS_NAVIGATION_DATA
      v = mrd.ArrayFlags(1);
    end
    function v = FIRST_IN_AVERAGE
      v = mrd.ArrayFlags(16);
    end
    function v = LAST_IN_AVERAGE
      v = mrd.ArrayFlags(32);
    end
    function v = FIRST_IN_SLICE
      v = mrd.ArrayFlags(64);
    end
    function v = LAST_IN_SLICE
      v = mrd.ArrayFlags(128);
    end
    function v = FIRST_IN_CONTRAST
      v = mrd.ArrayFlags(256);
    end
    function v = LAST_IN_CONTRAST
      v = mrd.ArrayFlags(512);
    end
    function v = FIRST_IN_PHASE
      v = mrd.ArrayFlags(1024);
    end
    function v = LAST_IN_PHASE
      v = mrd.ArrayFlags(2048);
    end
    function v = FIRST_IN_REPETITION
      v = mrd.ArrayFlags(4096);
    end
    function v = LAST_IN_REPETITION
      v = mrd.ArrayFlags(8192);
    end
    function v = FIRST_IN_SET
      v = mrd.ArrayFlags(16384);
    end
    function v = LAST_IN_SET
      v = mrd.ArrayFlags(32768);
    end

    function z = zeros(varargin)
      elem = mrd.ArrayFlags(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end

  methods
    function self = ArrayFlags(varargin)
      if nargin == 0
        value = 0;
      elseif nargin == 1
        value = varargin{1};
      else
        value = 0;
        for i = 1:nargin
          value = bitor(value, varargin{i});
        end
      end
      self@uint64(value);
    end

    function res = has_flags(self, flag)
      res = bitand(self, flag) == flag;
    end

    function res = with_flags(self, flag)
      res = mrd.ArrayFlags(bitor(self, flag));
    end

    function res = without_flags(self, flag)
      res = mrd.ArrayFlags(bitand(self, bitcmp(flag)));
    end
  end
end
