% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Block < handle
  % A sequence block that includes possible RF, gradient, and ADC events.
  properties
    % ID of the sequence block
    id
    % Duration of the block in units of Definitions.blockDurationRaster
    duration
    % ID of the RF event
    rf
    % ID of the gradient event on the X channel
    gx
    % ID of the gradient event on the Y channel
    gy
    % ID of the gradient event on the Z channel
    gz
    % ID of the ADC event
    adc
    % ID of the extension table entry
    ext
  end

  methods
    function self = Block(kwargs)
      arguments
        kwargs.id = int32(0);
        kwargs.duration = uint64(0);
        kwargs.rf = int32(0);
        kwargs.gx = int32(0);
        kwargs.gy = int32(0);
        kwargs.gz = int32(0);
        kwargs.adc = int32(0);
        kwargs.ext = int32(0);
      end
      self.id = kwargs.id;
      self.duration = kwargs.duration;
      self.rf = kwargs.rf;
      self.gx = kwargs.gx;
      self.gy = kwargs.gy;
      self.gz = kwargs.gz;
      self.adc = kwargs.adc;
      self.ext = kwargs.ext;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.Block") && ...
        isequal({self.id}, {other.id}) && ...
        isequal({self.duration}, {other.duration}) && ...
        isequal({self.rf}, {other.rf}) && ...
        isequal({self.gx}, {other.gx}) && ...
        isequal({self.gy}, {other.gy}) && ...
        isequal({self.gz}, {other.gz}) && ...
        isequal({self.adc}, {other.adc}) && ...
        isequal({self.ext}, {other.ext});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.Block();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
