% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef CalibrationMode < uint64
  methods (Static)
    function v = NOACCELERATION
      v = mrd.CalibrationMode(0);
    end
    function v = EMBEDDED
      v = mrd.CalibrationMode(1);
    end
    function v = INTERLEAVED
      v = mrd.CalibrationMode(2);
    end
    function v = SEPARATE
      v = mrd.CalibrationMode(3);
    end
    function v = EXTERNAL
      v = mrd.CalibrationMode(4);
    end
    function v = OTHER
      v = mrd.CalibrationMode(5);
    end

    function z = zeros(varargin)
      elem = mrd.CalibrationMode(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
