% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Calibration < uint64
  methods (Static)
    function v = SEPARABLE_2D
      v = mrd.Calibration(0);
    end
    function v = FULL_3D
      v = mrd.Calibration(1);
    end
    function v = OTHER
      v = mrd.Calibration(2);
    end

    function z = zeros(varargin)
      elem = mrd.Calibration(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
