% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef DiffusionDimension < uint64
  methods (Static)
    function v = AVERAGE
      v = mrd.DiffusionDimension(0);
    end
    function v = CONTRAST
      v = mrd.DiffusionDimension(1);
    end
    function v = PHASE
      v = mrd.DiffusionDimension(2);
    end
    function v = REPETITION
      v = mrd.DiffusionDimension(3);
    end
    function v = SET
      v = mrd.DiffusionDimension(4);
    end
    function v = SEGMENT
      v = mrd.DiffusionDimension(5);
    end
    function v = USER_0
      v = mrd.DiffusionDimension(6);
    end
    function v = USER_1
      v = mrd.DiffusionDimension(7);
    end
    function v = USER_2
      v = mrd.DiffusionDimension(8);
    end
    function v = USER_3
      v = mrd.DiffusionDimension(9);
    end
    function v = USER_4
      v = mrd.DiffusionDimension(10);
    end
    function v = USER_5
      v = mrd.DiffusionDimension(11);
    end
    function v = USER_6
      v = mrd.DiffusionDimension(12);
    end
    function v = USER_7
      v = mrd.DiffusionDimension(13);
    end

    function z = zeros(varargin)
      elem = mrd.DiffusionDimension(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
