% This file was generated by the "yardl" tool. DO NOT EDIT.

function a = GradientData(array)
  % gradient of defined direction stored as 1D array samples
  arguments
    array single
  end
  a = array;
end
