% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ImageArray < handle
  properties
    data
    headers
    meta
    waveforms
  end

  methods
    function self = ImageArray(kwargs)
      arguments
        kwargs.data = single.empty(0, 0, 0, 0, 0, 0, 0);
        kwargs.headers = mrd.ImageHeader.empty(0, 0, 0);
        kwargs.meta = mrd.ImageMeta.empty(0, 0, 0);
        kwargs.waveforms = mrd.WaveformUint32.empty();
      end
      self.data = kwargs.data;
      self.headers = kwargs.headers;
      self.meta = kwargs.meta;
      self.waveforms = kwargs.waveforms;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.ImageArray") && ...
        isequal(self.data, other.data) && ...
        isequal(self.headers, other.headers) && ...
        isequal(self.meta, other.meta) && ...
        isequal(self.waveforms, other.waveforms);
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.ImageArray();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
