% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Image < handle
  properties
    % Image header
    head
    % Image data array
    data
    % Meta attributes
    meta
  end

  methods
    function self = Image(kwargs)
      arguments
        kwargs.head;
        kwargs.data;
        kwargs.meta = dictionary;
      end
      if ~isfield(kwargs, "head")
        throw(yardl.TypeError("Missing required keyword argument 'head'"))
      end
      self.head = kwargs.head;
      if ~isfield(kwargs, "data")
        throw(yardl.TypeError("Missing required keyword argument 'data'"))
      end
      self.data = kwargs.data;
      self.meta = kwargs.meta;
    end

    function res = channels(self)
      res = size(self.data, ndims(self.data)-(0));
      return
    end

    function res = slices(self)
      res = size(self.data, ndims(self.data)-(1));
      return
    end

    function res = rows(self)
      res = size(self.data, ndims(self.data)-(2));
      return
    end

    function res = cols(self)
      res = size(self.data, ndims(self.data)-(3));
      return
    end

    function res = frequencies(self)
      res = size(self.data, ndims(self.data)-(4));
      return
    end


    function res = eq(self, other)
      res = ...
        isa(other, "mrd.Image") && ...
        isequal(self.head, other.head) && ...
        isequal(self.data, other.data) && ...
        isequal(self.meta, other.meta);
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end
  end

end
