% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ImageMetaValue < yardl.Union
  methods (Static)
    function res = String(value)
      res = mrd.ImageMetaValue(1, value);
    end

    function res = Int64(value)
      res = mrd.ImageMetaValue(2, value);
    end

    function res = Float64(value)
      res = mrd.ImageMetaValue(3, value);
    end

    function z = zeros(varargin)
      elem = mrd.ImageMetaValue(0, yardl.None);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end

  methods
    function res = isString(self)
      res = self.index == 1;
    end

    function res = isInt64(self)
      res = self.index == 2;
    end

    function res = isFloat64(self)
      res = self.index == 3;
    end

    function eq = eq(self, other)
      eq = isa(other, "mrd.ImageMetaValue") && isequal(self.index, other.index) && isequal(self.value, other.value);
    end

    function ne = ne(self, other)
      ne = ~self.eq(other);
    end

    function t = tag(self)
      tags_ = ["String", "Int64", "Float64"];
      t = tags_(self.index_);
    end
  end
end
