% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ImageType < uint64
  % EDIT: Image Type. Used flags to allow requests for multiple types with one command. Added 'quantitative' types
  methods (Static)
    function v = MAGNITUDE
      v = mrd.ImageType(1);
    end
    function v = PHASE
      v = mrd.ImageType(2);
    end
    function v = REAL
      v = mrd.ImageType(4);
    end
    function v = IMAG
      v = mrd.ImageType(8);
    end
    function v = COMPLEX
      v = mrd.ImageType(16);
    end
    function v = BITMAP
      v = mrd.ImageType(32);
    end
    function v = SPIN_DENSITY_MAP
      v = mrd.ImageType(64);
    end
    function v = T1_MAP
      v = mrd.ImageType(128);
    end
    function v = T2_MAP
      v = mrd.ImageType(256);
    end
    function v = T2STAR_MAP
      v = mrd.ImageType(512);
    end
    function v = ADC_MAP
      v = mrd.ImageType(1024);
    end
    function v = B0_MAP
      v = mrd.ImageType(2048);
    end
    function v = B1_MAP
      v = mrd.ImageType(4096);
    end
    function v = SENSITIVITY_MAP
      v = mrd.ImageType(8192);
    end
    function v = USER_MAP
      v = mrd.ImageType(16384);
    end

    function z = zeros(varargin)
      elem = mrd.ImageType(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
