% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ImageType < uint64
  methods (Static)
    function v = MAGNITUDE
      v = mrd.ImageType(1);
    end
    function v = PHASE
      v = mrd.ImageType(2);
    end
    function v = REAL
      v = mrd.ImageType(3);
    end
    function v = IMAG
      v = mrd.ImageType(4);
    end
    function v = COMPLEX
      v = mrd.ImageType(5);
    end
    function v = RGBA_MAP
      v = mrd.ImageType(6);
    end

    function z = zeros(varargin)
      elem = mrd.ImageType(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
