% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ImageType < uint64
  % image types to describe the data type of images or interpretation map with units
  methods (Static)
    function v = MAGNITUDE
      v = mrd.ImageType(1);
    end
    function v = PHASE
      v = mrd.ImageType(2);
    end
    function v = REAL
      v = mrd.ImageType(3);
    end
    function v = IMAG
      v = mrd.ImageType(4);
    end
    function v = COMPLEX
      v = mrd.ImageType(5);
    end
    function v = BITMAP
      v = mrd.ImageType(6);
    end
    function v = SPIN_DENSITY_MAP
      v = mrd.ImageType(7);
    end
    function v = T1_MAP
      v = mrd.ImageType(8);
    end
    function v = T2_MAP
      v = mrd.ImageType(9);
    end
    function v = T2STAR_MAP
      v = mrd.ImageType(10);
    end
    function v = ADC_MAP
      v = mrd.ImageType(11);
    end
    function v = B0_MAP
      v = mrd.ImageType(12);
    end
    function v = B1_MAP
      v = mrd.ImageType(13);
    end
    function v = SENSITIVITY_MAP
      v = mrd.ImageType(14);
    end
    function v = USER_MAP
      v = mrd.ImageType(15);
    end

    function z = zeros(varargin)
      elem = mrd.ImageType(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
