% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef InterleavingDimension < uint64
  methods (Static)
    function v = PHASE
      v = mrd.InterleavingDimension(0);
    end
    function v = REPETITION
      v = mrd.InterleavingDimension(1);
    end
    function v = CONTRAST
      v = mrd.InterleavingDimension(2);
    end
    function v = AVERAGE
      v = mrd.InterleavingDimension(3);
    end
    function v = OTHER
      v = mrd.InterleavingDimension(4);
    end

    function z = zeros(varargin)
      elem = mrd.InterleavingDimension(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
