% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef KspaceProtocolReaderBase < handle
  properties (Access=protected)
    state_
  end

  methods
    function self = KspaceProtocolReaderBase()
      self.state_ = 0;
    end

    function close(self)
      self.close_();
      if self.state_ ~= 2
        expected_method = self.state_to_method_name_(self.state_);
        throw(yardl.ProtocolError("Protocol reader closed before all data was consumed. Expected call to '%s'.", expected_method));
      end
    end

    % Ordinal 0
    function value = read_header(self)
      if self.state_ ~= 0
        self.raise_unexpected_state_(0);
      end

      value = self.read_header_();
      self.state_ = 1;
    end

    % Ordinal 1
    function more = has_kspace(self)
      if self.state_ ~= 1
        self.raise_unexpected_state_(1);
      end

      more = self.has_kspace_();
      if ~more
        self.state_ = 2;
      end
    end

    function value = read_kspace(self)
      if self.state_ ~= 1
        self.raise_unexpected_state_(1);
      end

      value = self.read_kspace_();
    end

    function copy_to(self, writer)
      writer.write_header(self.read_header());
      while self.has_kspace()
        item = self.read_kspace();
        writer.write_kspace({item});
      end
      writer.end_kspace();
    end
  end

  methods (Static)
    function res = schema()
      res = mrd.KspaceProtocolWriterBase.schema;
    end
  end

  methods (Abstract, Access=protected)
    read_header_(self)
    has_kspace_(self)
    read_kspace_(self)

    close_(self)
  end

  methods (Access=private)
    function raise_unexpected_state_(self, actual)
      actual_method = self.state_to_method_name_(actual);
      expected_method = self.state_to_method_name_(self.state_);
      throw(yardl.ProtocolError("Expected call to '%s' but received call to '%s'.", expected_method, actual_method));
    end

    function name = state_to_method_name_(self, state)
      if state == 0
        name = "read_header";
      elseif state == 1
        name = "read_kspace";
      else
        name = "<unknown>";
      end
    end
  end
end
