% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef LimitType < handle
  properties
    minimum
    maximum
    center
  end

  methods
    function self = LimitType(kwargs)
      arguments
        kwargs.minimum = uint32(0);
        kwargs.maximum = uint32(0);
        kwargs.center = uint32(0);
      end
      self.minimum = kwargs.minimum;
      self.maximum = kwargs.maximum;
      self.center = kwargs.center;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.LimitType") && ...
        isequal(self.minimum, other.minimum) && ...
        isequal(self.maximum, other.maximum) && ...
        isequal(self.center, other.center);
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.LimitType();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
