% This file was generated by the "yardl" tool. DO NOT EDIT.

% Protocol for serializing a noise covariance matrix
classdef MrdNoiseCovarianceReaderBase < handle
  properties (Access=protected)
    state_
  end

  methods
    function self = MrdNoiseCovarianceReaderBase()
      self.state_ = 0;
    end

    function close(self)
      self.close_();
      if self.state_ ~= 1
        expected_method = self.state_to_method_name_(self.state_);
        throw(yardl.ProtocolError("Protocol reader closed before all data was consumed. Expected call to '%s'.", expected_method));
      end
    end

    % Ordinal 0
    function value = read_noise_covariance(self)
      if self.state_ ~= 0
        self.raise_unexpected_state_(0);
      end

      value = self.read_noise_covariance_();
      self.state_ = 1;
    end

    function copy_to(self, writer)
      writer.write_noise_covariance(self.read_noise_covariance());
    end
  end

  methods (Static)
    function res = schema()
      res = mrd.MrdNoiseCovarianceWriterBase.schema;
    end
  end

  methods (Abstract, Access=protected)
    read_noise_covariance_(self)

    close_(self)
  end

  methods (Access=private)
    function raise_unexpected_state_(self, actual)
      actual_method = self.state_to_method_name_(actual);
      expected_method = self.state_to_method_name_(self.state_);
      throw(yardl.ProtocolError("Expected call to '%s' but received call to '%s'.", expected_method, actual_method));
    end

    function name = state_to_method_name_(self, state)
      if state == 0
        name = "read_noise_covariance";
      else
        name = "<unknown>";
      end
    end
  end
end
