% This file was generated by the "yardl" tool. DO NOT EDIT.

% Abstract writer for protocol MrdNoiseCovariance
% Protocol for serializing a noise covariance matrix
classdef (Abstract) MrdNoiseCovarianceWriterBase < handle
  properties (Access=protected)
    state_
  end

  methods
    function self = MrdNoiseCovarianceWriterBase()
      self.state_ = 0;
    end

    function close(self)
      self.close_();
      if self.state_ ~= 1
        expected_method = self.state_to_method_name_(self.state_);
        throw(yardl.ProtocolError("Protocol writer closed before all steps were called. Expected call to '%s'.", expected_method));
      end
    end

    % Ordinal 0
    function write_noise_covariance(self, value)
      if self.state_ ~= 0
        self.raise_unexpected_state_(0);
      end

      self.write_noise_covariance_(value);
      self.state_ = 1;
    end
  end

  methods (Static)
    function res = schema()
      res = string('{"protocol":{"name":"MrdNoiseCovariance","sequence":[{"name":"noiseCovariance","type":"Mrd.NoiseCovariance"}]},"types":[{"name":"CoilLabelType","fields":[{"name":"coilNumber","type":"uint32"},{"name":"coilName","type":"string"}]},{"name":"NoiseCovariance","fields":[{"name":"coilLabels","type":{"vector":{"items":"Mrd.CoilLabelType"}}},{"name":"receiverNoiseBandwidth","type":"float32"},{"name":"noiseDwellTimeUs","type":"float32"},{"name":"sampleCount","type":"size"},{"name":"matrix","type":{"array":{"items":"complexfloat32","dimensions":2}}}]}]}');
    end
  end

  methods (Abstract, Access=protected)
    write_noise_covariance_(self, value)

    end_stream_(self)
    close_(self)
  end

  methods (Access=private)
    function raise_unexpected_state_(self, actual)
      expected_method = self.state_to_method_name_(self.state_);
      actual_method = self.state_to_method_name_(actual);
      throw(yardl.ProtocolError("Expected call to '%s' but received call to '%s'", expected_method, actual_method));
    end

    function name = state_to_method_name_(self, state)
      if state == 0
        name = "write_noise_covariance";
      else
        name = '<unknown>';
      end
    end
  end
end
