% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef NdArray < handle
  properties
    head
    data
    meta
  end

  methods
    function self = NdArray(kwargs)
      arguments
        kwargs.head = mrd.NdArrayHeader();
        kwargs.data;
        kwargs.meta = yardl.Map;
      end
      self.head = kwargs.head;
      if ~isfield(kwargs, "data")
        throw(yardl.TypeError("Missing required keyword argument 'data'"))
      end
      self.data = kwargs.data;
      self.meta = kwargs.meta;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.NdArray") && ...
        isequal({self.head}, {other.head}) && ...
        isequal({self.data}, {other.data}) && ...
        isequal({self.meta}, {other.meta});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.NdArray(data=yardl.None);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
