% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef PatientPosition < uint64
  methods (Static)
    function v = H_FP
      v = mrd.PatientPosition(0);
    end
    function v = H_FS
      v = mrd.PatientPosition(1);
    end
    function v = H_FDR
      v = mrd.PatientPosition(2);
    end
    function v = H_FDL
      v = mrd.PatientPosition(3);
    end
    function v = F_FP
      v = mrd.PatientPosition(4);
    end
    function v = F_FS
      v = mrd.PatientPosition(5);
    end
    function v = F_FDR
      v = mrd.PatientPosition(6);
    end
    function v = F_FDL
      v = mrd.PatientPosition(7);
    end

    function z = zeros(varargin)
      elem = mrd.PatientPosition(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
