% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef PulseqDefinitions < handle
  % Pulseq definitions
  properties
    % Default raster time (dwell time) of the shaped gradient events, specified in seconds
    gradient_raster_time
    % Default raster time (dwell time) of the radio-frequency pulse shapes, specified in seconds
    radiofrequency_raster_time
    % The value defining the alignment of the ADC dwell times.
    % ADC dwell time must be integer multiple of the specified adcRasterTime.
    % adcRasterTime is specified in seconds
    adc_raster_time
    % The value defining the alignment of the block durations, specified in seconds;
    % the physical block duration must be integer multiple of the specified blockDurationRaster.
    % Block duration in the blocks section are specified in the units of blockDurationRaster
    block_duration_raster
    % Human-readable name of the sequence
    name
    % Field of view specified in meters.
    fov
    % Total duration of the sequence is seconds
    total_duration
    custom
  end

  methods
    function self = PulseqDefinitions(kwargs)
      arguments
        kwargs.gradient_raster_time = double(0);
        kwargs.radiofrequency_raster_time = double(0);
        kwargs.adc_raster_time = double(0);
        kwargs.block_duration_raster = double(0);
        kwargs.name = yardl.None;
        kwargs.fov = yardl.None;
        kwargs.total_duration = yardl.None;
        kwargs.custom = yardl.Map;
      end
      self.gradient_raster_time = kwargs.gradient_raster_time;
      self.radiofrequency_raster_time = kwargs.radiofrequency_raster_time;
      self.adc_raster_time = kwargs.adc_raster_time;
      self.block_duration_raster = kwargs.block_duration_raster;
      self.name = kwargs.name;
      self.fov = kwargs.fov;
      self.total_duration = kwargs.total_duration;
      self.custom = kwargs.custom;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.PulseqDefinitions") && ...
        isequal({self.gradient_raster_time}, {other.gradient_raster_time}) && ...
        isequal({self.radiofrequency_raster_time}, {other.radiofrequency_raster_time}) && ...
        isequal({self.adc_raster_time}, {other.adc_raster_time}) && ...
        isequal({self.block_duration_raster}, {other.block_duration_raster}) && ...
        isequal({self.name}, {other.name}) && ...
        isequal({self.fov}, {other.fov}) && ...
        isequal({self.total_duration}, {other.total_duration}) && ...
        isequal({self.custom}, {other.custom});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.PulseqDefinitions();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
