% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ReconAssembly < handle
  properties
    data
    ref
  end

  methods
    function self = ReconAssembly(kwargs)
      arguments
        kwargs.data = mrd.ReconBuffer();
        kwargs.ref = yardl.None;
      end
      self.data = kwargs.data;
      self.ref = kwargs.ref;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.ReconAssembly") && ...
        isequal(self.data, other.data) && ...
        isequal(self.ref, other.ref);
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.ReconAssembly();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
