% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ReferencedImageSequenceType < handle
  properties
    referenced_sop_instance_uid
  end

  methods
    function self = ReferencedImageSequenceType(kwargs)
      arguments
        kwargs.referenced_sop_instance_uid = string.empty();
      end
      self.referenced_sop_instance_uid = kwargs.referenced_sop_instance_uid;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.ReferencedImageSequenceType") && ...
        isequal(self.referenced_sop_instance_uid, other.referenced_sop_instance_uid);
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.ReferencedImageSequenceType();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
