% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef RFEvent < handle
  % An RF event
  properties
    % ID of the RF event
    id
    % Peak amplitude in Hz
    amp
    % Shape ID for the magnitude profile
    mag_id
    % Shape ID for the phase profile
    phase_id
    % Shape ID for the time sampling points, specified in the units of
    % RadiofrequencyRasterTime.
    % 0 means default time raster
    time_id
    % Time point in microseconds relative to the beginning of
    % the RF shape at which the effective rotation takes place
    center
    % Delay before starting the RF pulse, specified in microseconds
    delay
    % Frequency offset relative to the main system's frequency,
    % specified in parts per million (ppm)
    freq_ppm
    % Phase offset proportional to the main system's frequency,
    % specified in rad/MHz
    phase_ppm
    % Frequency offset in absolute units, specified in Hz
    freq_offset
    % Phase offset in absolute units, specified in radians
    phase_offset
    use
  end

  methods
    function self = RFEvent(kwargs)
      arguments
        kwargs.id = int32(0);
        kwargs.amp = double(0);
        kwargs.mag_id = int32(0);
        kwargs.phase_id = int32(0);
        kwargs.time_id = int32(0);
        kwargs.center = double(0);
        kwargs.delay = uint64(0);
        kwargs.freq_ppm = double(0);
        kwargs.phase_ppm = double(0);
        kwargs.freq_offset = double(0);
        kwargs.phase_offset = double(0);
        kwargs.use = mrd.RFPulseUse.UNDEFINED;
      end
      self.id = kwargs.id;
      self.amp = kwargs.amp;
      self.mag_id = kwargs.mag_id;
      self.phase_id = kwargs.phase_id;
      self.time_id = kwargs.time_id;
      self.center = kwargs.center;
      self.delay = kwargs.delay;
      self.freq_ppm = kwargs.freq_ppm;
      self.phase_ppm = kwargs.phase_ppm;
      self.freq_offset = kwargs.freq_offset;
      self.phase_offset = kwargs.phase_offset;
      self.use = kwargs.use;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.RFEvent") && ...
        isequal({self.id}, {other.id}) && ...
        isequal({self.amp}, {other.amp}) && ...
        isequal({self.mag_id}, {other.mag_id}) && ...
        isequal({self.phase_id}, {other.phase_id}) && ...
        isequal({self.time_id}, {other.time_id}) && ...
        isequal({self.center}, {other.center}) && ...
        isequal({self.delay}, {other.delay}) && ...
        isequal({self.freq_ppm}, {other.freq_ppm}) && ...
        isequal({self.phase_ppm}, {other.phase_ppm}) && ...
        isequal({self.freq_offset}, {other.freq_offset}) && ...
        isequal({self.phase_offset}, {other.phase_offset}) && ...
        isequal({self.use}, {other.use});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.RFEvent();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
