% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef RFPulseUse < uint64
  methods (Static)
    function v = UNDEFINED
      v = mrd.RFPulseUse(0);
    end
    function v = EXCITATION
      v = mrd.RFPulseUse(1);
    end
    function v = REFOCUSING
      v = mrd.RFPulseUse(2);
    end
    function v = INVERSION
      v = mrd.RFPulseUse(3);
    end
    function v = SATURATION
      v = mrd.RFPulseUse(4);
    end
    function v = PREPARATION
      v = mrd.RFPulseUse(5);
    end
    function v = OTHER
      v = mrd.RFPulseUse(6);
    end

    function z = zeros(varargin)
      elem = mrd.RFPulseUse(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
