% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Shape < handle
  % A list of samples that is potentially compressed.
  % If numSamples == size(data) then the shape is uncompressed.
  properties
    % ID of the shape
    id
    % Number of samples of the uncompressed shape
    num_samples
    % Samples of the (potentially) compressed shape. See the Pulseq specification for compression details.
    % In the spec, this should be float32, but PyPulseq uses float64.
    data
  end

  methods
    function self = Shape(kwargs)
      arguments
        kwargs.id = int32(0);
        kwargs.num_samples = uint64(0);
        kwargs.data = double.empty();
      end
      self.id = kwargs.id;
      self.num_samples = kwargs.num_samples;
      self.data = kwargs.data;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.Shape") && ...
        isequal({self.id}, {other.id}) && ...
        isequal({self.num_samples}, {other.num_samples}) && ...
        isequal({self.data}, {other.data});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.Shape();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
