% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef TrapezoidalGradient < handle
  % A trapezoidal gradient event
  properties
    % ID of the gradient event. Must be unique among all arbitrary and trapezoidal gradient events.
    id
    % Peak amplitude in Hz/m
    amp
    % Rise time of the trapezoid in microseconds
    rise
    % Flat-top time of the trapezoid in microseconds
    flat
    % Fall time of the trapezoid in microseconds
    fall
    % Delay before starting the gradient, specified in microseconds
    delay
  end

  methods
    function self = TrapezoidalGradient(kwargs)
      arguments
        kwargs.id = int32(0);
        kwargs.amp = double(0);
        kwargs.rise = uint64(0);
        kwargs.flat = uint64(0);
        kwargs.fall = uint64(0);
        kwargs.delay = uint64(0);
      end
      self.id = kwargs.id;
      self.amp = kwargs.amp;
      self.rise = kwargs.rise;
      self.flat = kwargs.flat;
      self.fall = kwargs.fall;
      self.delay = kwargs.delay;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.TrapezoidalGradient") && ...
        isequal({self.id}, {other.id}) && ...
        isequal({self.amp}, {other.amp}) && ...
        isequal({self.rise}, {other.rise}) && ...
        isequal({self.flat}, {other.flat}) && ...
        isequal({self.fall}, {other.fall}) && ...
        isequal({self.delay}, {other.delay});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.TrapezoidalGradient();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
