% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Waveform < handle
  properties
    % Bit field of flags. Currently unused
    flags
    % Unique ID for this measurement
    measurement_uid
    % Number of the acquisition after this waveform
    scan_counter
    % Starting timestamp of this waveform
    time_stamp_ns
    % Time between samples in nanoseconds
    sample_time_ns
    % ID matching the waveform in the MRD header
    waveform_id
    % Waveform sample array
    data
  end

  methods
    function self = Waveform(kwargs)
      arguments
        kwargs.flags = uint64(0);
        kwargs.measurement_uid = uint32(0);
        kwargs.scan_counter = uint32(0);
        kwargs.time_stamp_ns = uint64(0);
        kwargs.sample_time_ns = uint64(0);
        kwargs.waveform_id = uint32(0);
        kwargs.data;
      end
      self.flags = kwargs.flags;
      self.measurement_uid = kwargs.measurement_uid;
      self.scan_counter = kwargs.scan_counter;
      self.time_stamp_ns = kwargs.time_stamp_ns;
      self.sample_time_ns = kwargs.sample_time_ns;
      self.waveform_id = kwargs.waveform_id;
      if ~isfield(kwargs, "data")
        throw(yardl.TypeError("Missing required keyword argument 'data'"))
      end
      self.data = kwargs.data;
    end

    function res = channels(self)
      res = size(self.data, ndims(self.data)-(0));
      return
    end

    function res = number_of_samples(self)
      res = size(self.data, ndims(self.data)-(1));
      return
    end


    function res = eq(self, other)
      res = ...
        isa(other, "mrd.Waveform") && ...
        isequal({self.flags}, {other.flags}) && ...
        isequal({self.measurement_uid}, {other.measurement_uid}) && ...
        isequal({self.scan_counter}, {other.scan_counter}) && ...
        isequal({self.time_stamp_ns}, {other.time_stamp_ns}) && ...
        isequal({self.sample_time_ns}, {other.sample_time_ns}) && ...
        isequal({self.waveform_id}, {other.waveform_id}) && ...
        isequal({self.data}, {other.data});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.Waveform(data=yardl.None);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
