% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef WaveformType < uint64
  methods (Static)
    function v = ECG
      v = mrd.WaveformType(0);
    end
    function v = PULSE
      v = mrd.WaveformType(1);
    end
    function v = RESPIRATORY
      v = mrd.WaveformType(2);
    end
    function v = TRIGGER
      v = mrd.WaveformType(3);
    end
    function v = GRADIENTWAVEFORM
      v = mrd.WaveformType(4);
    end
    function v = OTHER
      v = mrd.WaveformType(5);
    end

    function z = zeros(varargin)
      elem = mrd.WaveformType(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
