% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef AccelerationFactorTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = AccelerationFactorTypeSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = yardl.binary.Uint32Serializer;
      self@yardl.binary.RecordSerializer('mrd.AccelerationFactorType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.AccelerationFactorType
      end
      self.write_(outstream, value.kspace_encoding_step_1, value.kspace_encoding_step_2);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.AccelerationFactorType(kspace_encoding_step_1=fields{1}, kspace_encoding_step_2=fields{2});
    end
  end
end
