% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef AcquisitionPrototypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = AcquisitionPrototypeSerializer()
      field_serializers{1} = mrd.binary.AcquisitionHeaderSerializer();
      field_serializers{2} = yardl.binary.NDArraySerializer(yardl.binary.Uint32Serializer, 1);
      self@yardl.binary.RecordSerializer('mrd.AcquisitionPrototype', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.AcquisitionPrototype
      end
      self.write_(outstream, value.head, value.data_sample_counts);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.AcquisitionPrototype(head=fields{1}, data_sample_counts=fields{2});
    end
  end
end
