% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef AcquisitionSerializer < yardl.binary.RecordSerializer
  methods
    function self = AcquisitionSerializer()
      field_serializers{1} = mrd.binary.AcquisitionHeaderSerializer();
      field_serializers{2} = yardl.binary.NDArraySerializer(yardl.binary.Complexfloat32Serializer, 2);
      field_serializers{3} = yardl.binary.NDArraySerializer(yardl.binary.Float32Serializer, 1);
      field_serializers{4} = yardl.binary.NDArraySerializer(yardl.binary.Float32Serializer, 2);
      self@yardl.binary.RecordSerializer('mrd.Acquisition', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.Acquisition
      end
      self.write_(outstream, value.head, value.data, value.phase, value.trajectory);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.Acquisition(head=fields{1}, data=fields{2}, phase=fields{3}, trajectory=fields{4});
    end
  end
end
