% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ADCEventSerializer < yardl.binary.RecordSerializer
  methods
    function self = ADCEventSerializer()
      field_serializers{1} = yardl.binary.Int32Serializer;
      field_serializers{2} = yardl.binary.Uint64Serializer;
      field_serializers{3} = yardl.binary.Float32Serializer;
      field_serializers{4} = yardl.binary.Uint64Serializer;
      field_serializers{5} = yardl.binary.Float64Serializer;
      field_serializers{6} = yardl.binary.Float64Serializer;
      field_serializers{7} = yardl.binary.Float64Serializer;
      field_serializers{8} = yardl.binary.Float64Serializer;
      field_serializers{9} = yardl.binary.Int32Serializer;
      self@yardl.binary.RecordSerializer('mrd.ADCEvent', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.ADCEvent
      end
      self.write_(outstream, value.id, value.num, value.dwell, value.delay, value.freq_ppm, value.phase_ppm, value.freq, value.phase, value.phase_shape_id);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.ADCEvent(id=fields{1}, num=fields{2}, dwell=fields{3}, delay=fields{4}, freq_ppm=fields{5}, phase_ppm=fields{6}, freq=fields{7}, phase=fields{8}, phase_shape_id=fields{9});
    end
  end
end
