% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ArbitraryGradientSerializer < yardl.binary.RecordSerializer
  methods
    function self = ArbitraryGradientSerializer()
      field_serializers{1} = yardl.binary.Int32Serializer;
      field_serializers{2} = yardl.binary.Float64Serializer;
      field_serializers{3} = yardl.binary.Float64Serializer;
      field_serializers{4} = yardl.binary.Float64Serializer;
      field_serializers{5} = yardl.binary.Int32Serializer;
      field_serializers{6} = yardl.binary.Int32Serializer;
      field_serializers{7} = yardl.binary.Uint64Serializer;
      self@yardl.binary.RecordSerializer('mrd.ArbitraryGradient', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.ArbitraryGradient
      end
      self.write_(outstream, value.id, value.amp, value.first, value.last, value.shape_id, value.time_id, value.delay);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.ArbitraryGradient(id=fields{1}, amp=fields{2}, first=fields{3}, last=fields{4}, shape_id=fields{5}, time_id=fields{6}, delay=fields{7});
    end
  end
end
