% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ArrayHeaderSerializer < yardl.binary.RecordSerializer
  methods
    function self = ArrayHeaderSerializer()
      field_serializers{1} = yardl.binary.VectorSerializer(yardl.binary.EnumSerializer('mrd.ArrayDimension', @mrd.ArrayDimension, yardl.binary.Int32Serializer));
      field_serializers{2} = yardl.binary.OptionalSerializer(yardl.binary.EnumSerializer('mrd.ArrayType', @mrd.ArrayType, yardl.binary.Int32Serializer));
      field_serializers{3} = yardl.binary.MapSerializer(yardl.binary.StringSerializer, yardl.binary.VectorSerializer(yardl.binary.UnionSerializer('mrd.ArrayMetaValue', {yardl.binary.StringSerializer, yardl.binary.Int64Serializer, yardl.binary.Float64Serializer}, {@mrd.ArrayMetaValue.String, @mrd.ArrayMetaValue.Int64, @mrd.ArrayMetaValue.Float64})));
      self@yardl.binary.RecordSerializer('mrd.ArrayHeader', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.ArrayHeader
      end
      self.write_(outstream, value.dimension_labels, value.array_type, value.meta);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.ArrayHeader(dimension_labels=fields{1}, array_type=fields{2}, meta=fields{3});
    end
  end
end
