% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef BlockSerializer < yardl.binary.RecordSerializer
  methods
    function self = BlockSerializer()
      field_serializers{1} = yardl.binary.Int32Serializer;
      field_serializers{2} = yardl.binary.Uint64Serializer;
      field_serializers{3} = yardl.binary.Int32Serializer;
      field_serializers{4} = yardl.binary.Int32Serializer;
      field_serializers{5} = yardl.binary.Int32Serializer;
      field_serializers{6} = yardl.binary.Int32Serializer;
      field_serializers{7} = yardl.binary.Int32Serializer;
      field_serializers{8} = yardl.binary.Int32Serializer;
      self@yardl.binary.RecordSerializer('mrd.Block', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.Block
      end
      self.write_(outstream, value.id, value.duration, value.rf, value.gx, value.gy, value.gz, value.adc, value.ext);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.Block(id=fields{1}, duration=fields{2}, rf=fields{3}, gx=fields{4}, gy=fields{5}, gz=fields{6}, adc=fields{7}, ext=fields{8});
    end
  end
end
