% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef CoilLabelTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = CoilLabelTypeSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = yardl.binary.StringSerializer;
      self@yardl.binary.RecordSerializer('mrd.CoilLabelType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.CoilLabelType
      end
      self.write_(outstream, value.coil_number, value.coil_name);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.CoilLabelType(coil_number=fields{1}, coil_name=fields{2});
    end
  end
end
