% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef EncodingLimitsTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = EncodingLimitsTypeSerializer()
      field_serializers{1} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{2} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{3} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{4} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{5} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{6} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{7} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{8} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{9} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{10} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{11} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{12} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{13} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{14} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{15} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{16} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{17} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      field_serializers{18} = yardl.binary.OptionalSerializer(mrd.binary.LimitTypeSerializer());
      self@yardl.binary.RecordSerializer('mrd.EncodingLimitsType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.EncodingLimitsType
      end
      self.write_(outstream, value.kspace_encoding_step_0, value.kspace_encoding_step_1, value.kspace_encoding_step_2, value.average, value.slice, value.contrast, value.phase, value.repetition, value.set, value.segment, value.user_0, value.user_1, value.user_2, value.user_3, value.user_4, value.user_5, value.user_6, value.user_7);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.EncodingLimitsType(kspace_encoding_step_0=fields{1}, kspace_encoding_step_1=fields{2}, kspace_encoding_step_2=fields{3}, average=fields{4}, slice=fields{5}, contrast=fields{6}, phase=fields{7}, repetition=fields{8}, set=fields{9}, segment=fields{10}, user_0=fields{11}, user_1=fields{12}, user_2=fields{13}, user_3=fields{14}, user_4=fields{15}, user_5=fields{16}, user_6=fields{17}, user_7=fields{18});
    end
  end
end
