% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef EncodingSpaceTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = EncodingSpaceTypeSerializer()
      field_serializers{1} = mrd.binary.MatrixSizeTypeSerializer();
      field_serializers{2} = mrd.binary.FieldOfViewMmSerializer();
      self@yardl.binary.RecordSerializer('mrd.EncodingSpaceType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.EncodingSpaceType
      end
      self.write_(outstream, value.matrix_size, value.field_of_view_mm);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.EncodingSpaceType(matrix_size=fields{1}, field_of_view_mm=fields{2});
    end
  end
end
