% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ExperimentalConditionsTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = ExperimentalConditionsTypeSerializer()
      field_serializers{1} = yardl.binary.Int64Serializer;
      self@yardl.binary.RecordSerializer('mrd.ExperimentalConditionsType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.ExperimentalConditionsType
      end
      self.write_(outstream, value.h1resonance_frequency_hz);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.ExperimentalConditionsType(h1resonance_frequency_hz=fields{1});
    end
  end
end
