% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef GradientSerializer < yardl.binary.RecordSerializer
  methods
    function self = GradientSerializer()
      field_serializers{1} = mrd.binary.GradientHeaderSerializer();
      field_serializers{2} = yardl.binary.NDArraySerializer(yardl.binary.Float32Serializer, 1);
      self@yardl.binary.RecordSerializer('mrd.Gradient', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.Gradient
      end
      self.write_(outstream, value.head, value.data);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.Gradient(head=fields{1}, data=fields{2});
    end
  end
end
