% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ImageMetaDataSerializer < yardl.binary.RecordSerializer
  methods
    function self = ImageMetaDataSerializer()
      field_serializers{1} = yardl.binary.StringSerializer;
      field_serializers{2} = yardl.binary.StringSerializer;
      self@yardl.binary.RecordSerializer('mrd.ImageMetaData', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.ImageMetaData
      end
      self.write_(outstream, value.name, value.value);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.ImageMetaData(name=fields{1}, value=fields{2});
    end
  end
end
