% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ImageArraySerializer < yardl.binary.RecordSerializer
  methods
    function self = ImageArraySerializer()
      field_serializers{1} = yardl.binary.NDArraySerializer(yardl.binary.Complexfloat32Serializer, 7);
      field_serializers{2} = yardl.binary.NDArraySerializer(mrd.binary.ImageHeaderSerializer(), 3);
      field_serializers{3} = yardl.binary.NDArraySerializer(yardl.binary.MapSerializer(yardl.binary.StringSerializer, yardl.binary.VectorSerializer(yardl.binary.UnionSerializer('mrd.ImageMetaValue', {yardl.binary.StringSerializer, yardl.binary.Int64Serializer, yardl.binary.Float64Serializer}, {@mrd.ImageMetaValue.String, @mrd.ImageMetaValue.Int64, @mrd.ImageMetaValue.Float64}))), 3);
      field_serializers{4} = yardl.binary.VectorSerializer(mrd.binary.WaveformSerializer(yardl.binary.Uint32Serializer));
      self@yardl.binary.RecordSerializer('mrd.ImageArray', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.ImageArray
      end
      self.write_(outstream, value.data, value.headers, value.meta, value.waveforms);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.ImageArray(data=fields{1}, headers=fields{2}, meta=fields{3}, waveforms=fields{4});
    end
  end
end
