% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef LimitTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = LimitTypeSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = yardl.binary.Uint32Serializer;
      field_serializers{3} = yardl.binary.Uint32Serializer;
      self@yardl.binary.RecordSerializer('mrd.LimitType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.LimitType
      end
      self.write_(outstream, value.minimum, value.maximum, value.center);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.LimitType(minimum=fields{1}, maximum=fields{2}, center=fields{3});
    end
  end
end
