% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef MinMaxStatSerializer < yardl.binary.RecordSerializer
  methods
    function self = MinMaxStatSerializer()
      field_serializers{1} = yardl.binary.Uint32Serializer;
      field_serializers{2} = yardl.binary.Uint32Serializer;
      self@yardl.binary.RecordSerializer('mrd.MinMaxStat', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.MinMaxStat
      end
      self.write_(outstream, value.minimum, value.maximum);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.MinMaxStat(minimum=fields{1}, maximum=fields{2});
    end
  end
end
