% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef MrdNoiseCovarianceReader < yardl.binary.BinaryProtocolReader & mrd.MrdNoiseCovarianceReaderBase
  % Binary reader for the MrdNoiseCovariance protocol
  % Protocol for serializing a noise covariance matrix
  properties (Access=protected)
    noise_covariance_serializer
  end

  methods
    function self = MrdNoiseCovarianceReader(filename, options)
      arguments
        filename (1,1) string
        options.skip_completed_check (1,1) logical = false
      end
      self@mrd.MrdNoiseCovarianceReaderBase(skip_completed_check=options.skip_completed_check);
      self@yardl.binary.BinaryProtocolReader(filename, mrd.MrdNoiseCovarianceReaderBase.schema);
      self.noise_covariance_serializer = mrd.binary.NoiseCovarianceSerializer();
    end
  end

  methods (Access=protected)
    function value = read_noise_covariance_(self)
      value = self.noise_covariance_serializer.read(self.stream_);
    end
  end
end
