% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef MrdReader < yardl.binary.BinaryProtocolReader & mrd.MrdReaderBase
  % Binary reader for the Mrd protocol
  % The MRD Protocol
  properties (Access=protected)
    header_serializer
    data_serializer
  end

  methods
    function self = MrdReader(filename, options)
      arguments
        filename (1,1) string
        options.skip_completed_check (1,1) logical = false
      end
      self@mrd.MrdReaderBase(skip_completed_check=options.skip_completed_check);
      self@yardl.binary.BinaryProtocolReader(filename, mrd.MrdReaderBase.schema);
      self.header_serializer = yardl.binary.OptionalSerializer(mrd.binary.HeaderSerializer());
      self.data_serializer = yardl.binary.StreamSerializer(yardl.binary.UnionSerializer('mrd.StreamItem', {mrd.binary.AcquisitionSerializer(), mrd.binary.WaveformSerializer(yardl.binary.Uint32Serializer), mrd.binary.ImageSerializer(yardl.binary.Uint16Serializer), mrd.binary.ImageSerializer(yardl.binary.Int16Serializer), mrd.binary.ImageSerializer(yardl.binary.Uint32Serializer), mrd.binary.ImageSerializer(yardl.binary.Int32Serializer), mrd.binary.ImageSerializer(yardl.binary.Float32Serializer), mrd.binary.ImageSerializer(yardl.binary.Float64Serializer), mrd.binary.ImageSerializer(yardl.binary.Complexfloat32Serializer), mrd.binary.ImageSerializer(yardl.binary.Complexfloat64Serializer), mrd.binary.AcquisitionBucketSerializer(), mrd.binary.ReconDataSerializer(), mrd.binary.ImageArraySerializer(), mrd.binary.NdArraySerializer(yardl.binary.Uint16Serializer), mrd.binary.NdArraySerializer(yardl.binary.Int16Serializer), mrd.binary.NdArraySerializer(yardl.binary.Uint32Serializer), mrd.binary.NdArraySerializer(yardl.binary.Int32Serializer), mrd.binary.NdArraySerializer(yardl.binary.Float32Serializer), mrd.binary.NdArraySerializer(yardl.binary.Float64Serializer), mrd.binary.NdArraySerializer(yardl.binary.Complexfloat32Serializer), mrd.binary.NdArraySerializer(yardl.binary.Complexfloat64Serializer)}, {@mrd.StreamItem.Acquisition, @mrd.StreamItem.WaveformUint32, @mrd.StreamItem.ImageUint16, @mrd.StreamItem.ImageInt16, @mrd.StreamItem.ImageUint32, @mrd.StreamItem.ImageInt32, @mrd.StreamItem.ImageFloat, @mrd.StreamItem.ImageDouble, @mrd.StreamItem.ImageComplexFloat, @mrd.StreamItem.ImageComplexDouble, @mrd.StreamItem.AcquisitionBucket, @mrd.StreamItem.ReconData, @mrd.StreamItem.ImageArray, @mrd.StreamItem.NdArrayUint16, @mrd.StreamItem.NdArrayInt16, @mrd.StreamItem.NdArrayUint32, @mrd.StreamItem.NdArrayInt32, @mrd.StreamItem.NdArrayFloat, @mrd.StreamItem.NdArrayDouble, @mrd.StreamItem.NdArrayComplexFloat, @mrd.StreamItem.NdArrayComplexDouble}));
    end
  end

  methods (Access=protected)
    function value = read_header_(self)
      value = self.header_serializer.read(self.stream_);
    end

    function more = has_data_(self)
      more = self.data_serializer.hasnext(self.stream_);
    end

    function value = read_data_(self)
      value = self.data_serializer.read(self.stream_);
    end
  end
end
