% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef PulseHeaderSerializer < yardl.binary.RecordSerializer
  methods
    function self = PulseHeaderSerializer()
      field_serializers{1} = yardl.binary.Uint64Serializer;
      field_serializers{2} = yardl.binary.VectorSerializer(yardl.binary.Uint32Serializer);
      field_serializers{3} = yardl.binary.Uint32Serializer;
      field_serializers{4} = yardl.binary.OptionalSerializer(yardl.binary.VectorSerializer(yardl.binary.Float32Serializer));
      self@yardl.binary.RecordSerializer('mrd.PulseHeader', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.PulseHeader
      end
      self.write_(outstream, value.pulse_time_stamp_ns, value.channel_order, value.sample_time_ns, value.pulse_calibration);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.PulseHeader(pulse_time_stamp_ns=fields{1}, channel_order=fields{2}, sample_time_ns=fields{3}, pulse_calibration=fields{4});
    end
  end
end
