% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ReconAssemblySerializer < yardl.binary.RecordSerializer
  methods
    function self = ReconAssemblySerializer()
      field_serializers{1} = mrd.binary.ReconBufferSerializer();
      field_serializers{2} = yardl.binary.OptionalSerializer(mrd.binary.ReconBufferSerializer());
      self@yardl.binary.RecordSerializer('mrd.ReconAssembly', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.ReconAssembly
      end
      self.write_(outstream, value.data, value.ref);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.ReconAssembly(data=fields{1}, ref=fields{2});
    end
  end
end
