% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ReconBitSerializer < yardl.binary.RecordSerializer
  methods
    function self = ReconBitSerializer()
      field_serializers{1} = mrd.binary.BufferedDataSerializer();
      field_serializers{2} = yardl.binary.OptionalSerializer(mrd.binary.BufferedDataSerializer());
      self@yardl.binary.RecordSerializer('mrd.ReconBit', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.ReconBit
      end
      self.write_(outstream, value.data, value.ref);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.ReconBit(data=fields{1}, ref=fields{2});
    end
  end
end
