% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef SamplingDescriptionSerializer < yardl.binary.RecordSerializer
  methods
    function self = SamplingDescriptionSerializer()
      field_serializers{1} = mrd.binary.FieldOfViewMmSerializer();
      field_serializers{2} = mrd.binary.FieldOfViewMmSerializer();
      field_serializers{3} = mrd.binary.MatrixSizeTypeSerializer();
      field_serializers{4} = mrd.binary.MatrixSizeTypeSerializer();
      field_serializers{5} = mrd.binary.SamplingLimitsSerializer();
      self@yardl.binary.RecordSerializer('mrd.SamplingDescription', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.SamplingDescription
      end
      self.write_(outstream, value.encoded_fov, value.recon_fov, value.encoded_matrix, value.recon_matrix, value.sampling_limits);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.SamplingDescription(encoded_fov=fields{1}, recon_fov=fields{2}, encoded_matrix=fields{3}, recon_matrix=fields{4}, sampling_limits=fields{5});
    end
  end
end
