% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ShapeSerializer < yardl.binary.RecordSerializer
  methods
    function self = ShapeSerializer()
      field_serializers{1} = yardl.binary.Int32Serializer;
      field_serializers{2} = yardl.binary.Uint64Serializer;
      field_serializers{3} = yardl.binary.NDArraySerializer(yardl.binary.Float64Serializer, 1);
      self@yardl.binary.RecordSerializer('mrd.Shape', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.Shape
      end
      self.write_(outstream, value.id, value.num_samples, value.data);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.Shape(id=fields{1}, num_samples=fields{2}, data=fields{3});
    end
  end
end
