% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef StudyInformationTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = StudyInformationTypeSerializer()
      field_serializers{1} = yardl.binary.OptionalSerializer(yardl.binary.DateSerializer);
      field_serializers{2} = yardl.binary.OptionalSerializer(yardl.binary.TimeSerializer);
      field_serializers{3} = yardl.binary.OptionalSerializer(yardl.binary.StringSerializer);
      field_serializers{4} = yardl.binary.OptionalSerializer(yardl.binary.Int64Serializer);
      field_serializers{5} = yardl.binary.OptionalSerializer(yardl.binary.StringSerializer);
      field_serializers{6} = yardl.binary.OptionalSerializer(yardl.binary.StringSerializer);
      field_serializers{7} = yardl.binary.OptionalSerializer(yardl.binary.StringSerializer);
      field_serializers{8} = yardl.binary.OptionalSerializer(yardl.binary.StringSerializer);
      self@yardl.binary.RecordSerializer('mrd.StudyInformationType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.StudyInformationType
      end
      self.write_(outstream, value.study_date, value.study_time, value.study_id, value.accession_number, value.referring_physician_name, value.study_description, value.study_instance_uid, value.body_part_examined);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.StudyInformationType(study_date=fields{1}, study_time=fields{2}, study_id=fields{3}, accession_number=fields{4}, referring_physician_name=fields{5}, study_description=fields{6}, study_instance_uid=fields{7}, body_part_examined=fields{8});
    end
  end
end
