% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef TrapezoidalGradientSerializer < yardl.binary.RecordSerializer
  methods
    function self = TrapezoidalGradientSerializer()
      field_serializers{1} = yardl.binary.Int32Serializer;
      field_serializers{2} = yardl.binary.Float64Serializer;
      field_serializers{3} = yardl.binary.Uint64Serializer;
      field_serializers{4} = yardl.binary.Uint64Serializer;
      field_serializers{5} = yardl.binary.Uint64Serializer;
      field_serializers{6} = yardl.binary.Uint64Serializer;
      self@yardl.binary.RecordSerializer('mrd.TrapezoidalGradient', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.TrapezoidalGradient
      end
      self.write_(outstream, value.id, value.amp, value.rise, value.flat, value.fall, value.delay);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.TrapezoidalGradient(id=fields{1}, amp=fields{2}, rise=fields{3}, flat=fields{4}, fall=fields{5}, delay=fields{6});
    end
  end
end
