% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef UserParametersTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = UserParametersTypeSerializer()
      field_serializers{1} = yardl.binary.VectorSerializer(mrd.binary.UserParameterLongTypeSerializer());
      field_serializers{2} = yardl.binary.VectorSerializer(mrd.binary.UserParameterDoubleTypeSerializer());
      field_serializers{3} = yardl.binary.VectorSerializer(mrd.binary.UserParameterStringTypeSerializer());
      field_serializers{4} = yardl.binary.VectorSerializer(mrd.binary.UserParameterBase64TypeSerializer());
      self@yardl.binary.RecordSerializer('mrd.UserParametersType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.UserParametersType
      end
      self.write_(outstream, value.user_parameter_long, value.user_parameter_double, value.user_parameter_string, value.user_parameter_base64);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.UserParametersType(user_parameter_long=fields{1}, user_parameter_double=fields{2}, user_parameter_string=fields{3}, user_parameter_base64=fields{4});
    end
  end
end
