% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef WaveformInformationTypeSerializer < yardl.binary.RecordSerializer
  methods
    function self = WaveformInformationTypeSerializer()
      field_serializers{1} = yardl.binary.StringSerializer;
      field_serializers{2} = yardl.binary.EnumSerializer('mrd.WaveformType', @mrd.WaveformType, yardl.binary.Int32Serializer);
      field_serializers{3} = mrd.binary.UserParametersTypeSerializer();
      self@yardl.binary.RecordSerializer('mrd.WaveformInformationType', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.WaveformInformationType
      end
      self.write_(outstream, value.waveform_name, value.waveform_type, value.user_parameters);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.WaveformInformationType(waveform_name=fields{1}, waveform_type=fields{2}, user_parameters=fields{3});
    end
  end
end
