# This file was generated by the "yardl" tool. DO NOT EDIT.

# pyright: reportUnusedImport=false
from typing import Tuple as _Tuple
import re as _re
import numpy as _np

_MIN_NUMPY_VERSION = (1, 22, 0)

def _parse_version(version: str) -> _Tuple[int, ...]:
    try:
        return tuple(map(int, version.split(".")))
    except ValueError:
        # ignore any prerelease suffix
        version = _re.sub(r"[^0-9.]", "", version)
        return tuple(map(int, version.split(".")))

if _parse_version(_np.__version__) < _MIN_NUMPY_VERSION:
    raise ImportError(f"Your installed numpy version is {_np.__version__}, but version >= {'.'.join(str(i) for i in _MIN_NUMPY_VERSION)} is required.")

from .yardl_types import *
from .types import (
    AccelerationFactorType,
    Acquisition,
    AcquisitionBucket,
    AcquisitionBucketStats,
    AcquisitionData,
    AcquisitionFlags,
    AcquisitionHeader,
    AcquisitionSystemInformationType,
    BufferedData,
    Calibration,
    CalibrationMode,
    CoilLabelType,
    DiffusionDimension,
    DiffusionType,
    EncodingCounters,
    EncodingLimitsType,
    EncodingSpaceType,
    EncodingType,
    ExperimentalConditionsType,
    FieldOfViewMm,
    GradientDirectionType,
    Header,
    Image,
    ImageArray,
    ImageComplexDouble,
    ImageComplexFloat,
    ImageData,
    ImageDouble,
    ImageFlags,
    ImageFloat,
    ImageHeader,
    ImageInt,
    ImageInt16,
    ImageMeta,
    ImageMetaValue,
    ImageType,
    ImageUint,
    ImageUint16,
    InterleavingDimension,
    Kspace,
    KspaceData,
    LimitType,
    MaskData,
    MatrixSizeType,
    MeasurementDependencyType,
    MeasurementInformationType,
    MinMaxStat,
    MultibandSpacingType,
    MultibandType,
    NoiseCovariance,
    ParallelImagingType,
    PatientGender,
    PatientPosition,
    ReconBit,
    ReconData,
    ReferencedImageSequenceType,
    SamplingDescription,
    SamplingLimits,
    SequenceParametersType,
    StreamItem,
    StudyInformationType,
    SubjectInformationType,
    ThreeDimensionalFloat,
    Trajectory,
    TrajectoryData,
    TrajectoryDescriptionType,
    UserParameterBase64Type,
    UserParameterDoubleType,
    UserParameterLongType,
    UserParameterStringType,
    UserParametersType,
    Waveform,
    WaveformInformationType,
    WaveformSamples,
    WaveformType,
    WaveformUint32,
    get_dtype,
)
from .protocols import (
    KspaceProtocolReaderBase,
    KspaceProtocolWriterBase,
    MrdNoiseCovarianceReaderBase,
    MrdNoiseCovarianceWriterBase,
    MrdReaderBase,
    MrdWriterBase,
)
from .binary import (
    BinaryKspaceProtocolReader,
    BinaryKspaceProtocolWriter,
    BinaryMrdNoiseCovarianceReader,
    BinaryMrdNoiseCovarianceWriter,
    BinaryMrdReader,
    BinaryMrdWriter,
)
from .ndjson import (
    NDJsonKspaceProtocolReader,
    NDJsonKspaceProtocolWriter,
    NDJsonMrdNoiseCovarianceReader,
    NDJsonMrdNoiseCovarianceWriter,
    NDJsonMrdReader,
    NDJsonMrdWriter,
)
