name: Configure MRD Build Environment
description: Configures the conda development environment

# The following inputs are currently expected environment variables:
# YARDL_VERSION
# CONDA_CACHE_NUMBER

runs:
  using: composite
  steps:
    - name: Install Yardl
      shell: bash
      run: |
        OS=$([ "${{ runner.os }}" = "macOS" ] && echo "darwin" || echo "linux")
        ARCH=$([ "${{ runner.arch }}" = "ARM64" ] && echo "arm64" || echo "x86_64")
        mkdir -p "/tmp/yardl_${YARDL_VERSION}_${OS}_${ARCH}"
        cd "/tmp/yardl_${YARDL_VERSION}_${OS}_${ARCH}"
        wget --quiet "https://github.com/microsoft/yardl/releases/download/v${YARDL_VERSION}/yardl_${YARDL_VERSION}_${OS}_${ARCH}.tar.gz"
        tar -xzf "yardl_${YARDL_VERSION}_${OS}_${ARCH}.tar.gz"
        pwd >> $GITHUB_PATH

    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        # Do not specify environment file - see Cache step below
        activate-environment: mrd

    - name: Get Date
      id: get-date
      shell: bash
      run: echo "DATE=$(date -u +'%Y%m%d')" >> $GITHUB_ENV

    - name: Cache Conda Env
      id: cache-conda
      uses: actions/cache@v3
      with:
        path: ${{ env.CONDA }}/envs
        key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            hashFiles('environment.yml') }}-${{
            env.DATE }}-${{
            env.CONDA_CACHE_NUMBER }}

    - name: Update Environment
      shell: bash -el {0}
      run: |
        grep -v '# local' environment.yml > /tmp/environment-ci.yml
        conda env update -n mrd -f /tmp/environment-ci.yml
      if: steps.cache-conda.outputs.cache-hit != 'true'
